'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { AlertCircle, ArrowLeft, Check, Loader2, PackageCheck, RotateCcw, Wallet } from 'lucide-react';
import { useAuthStore } from '@/store/authStore';
import { getApiError } from '@/lib/api';
import { purchasesAPI, purchaseMoney, type GoodsReceivedNote, type PaymentMethodOption, type PurchaseOrder, type PurchaseReturn } from '@/lib/api/purchases';
import { notify } from '@/components/ui/AppToaster';

const input='min-h-10 w-full rounded-xl border border-[#dfe2da] bg-white px-3 text-sm outline-none focus:border-[#829600] focus:ring-2 focus:ring-[#d8f04b]/40';
type ReceiptLine={purchaseOrderItemId:string;receivedQuantity:string;acceptedQuantity:string;rejectedQuantity:string;damageQuantity:string;batchNumber:string;expiryDate:string};
type GrnEditLine={purchaseOrderItemId:string;receivedQuantity:string;acceptedQuantity:string;rejectedQuantity:string;damageQuantity:string};
const returnReasons=['DEFECTIVE','EXPIRED','WRONG_ITEM','OVERAGE','OTHER'] as const;

export default function PurchaseOrderDetailPage(){
  const params=useParams<{id:string}>(); const id=params.id; const permissions=useAuthStore(s=>s.user?.permissions??[]);
  const [po,setPo]=useState<PurchaseOrder|null>(null);const [grns,setGrns]=useState<GoodsReceivedNote[]>([]);const [returns,setReturns]=useState<PurchaseReturn[]>([]);const [methods,setMethods]=useState<PaymentMethodOption[]>([]);
  const [receipt,setReceipt]=useState<ReceiptLine[]>([]);const [payAmount,setPayAmount]=useState('');const [methodId,setMethodId]=useState('');const [returnItem,setReturnItem]=useState('');const [returnQty,setReturnQty]=useState('');const [returnReason,setReturnReason]=useState<(typeof returnReasons)[number]>('DEFECTIVE');
  const [editingGrn,setEditingGrn]=useState('');const [grnEditLines,setGrnEditLines]=useState<GrnEditLine[]>([]);
  const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [cancelDialog,setCancelDialog]=useState(false);const [cancelReason,setCancelReason]=useState('');const [cancelReasonError,setCancelReasonError]=useState('');
  const load=useCallback(async()=>{if(!permissions.includes('purchases.view')){setLoading(false);return}setLoading(true);setError('');try{const [order,notes,ret]=await Promise.all([purchasesAPI.order(id),purchasesAPI.grns(id),purchasesAPI.returns(id)]);setPo(order);setGrns(notes);setReturns(ret);setReceipt(order.items.filter(i=>i.outstandingQty>0).map(i=>({purchaseOrderItemId:i.id,receivedQuantity:String(i.outstandingQty),acceptedQuantity:String(i.outstandingQty),rejectedQuantity:'0',damageQuantity:'0',batchNumber:'',expiryDate:''})));}catch(e){setError(getApiError(e,'Could not load this purchase order.'))}finally{setLoading(false)}},[id,permissions]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(permissions.includes('settings.view'))purchasesAPI.paymentMethods().then(rows=>{setMethods(rows.filter(x=>x.isActive));if(rows.length)setMethodId(rows[0].id)}).catch(()=>undefined)},[permissions]);
  async function act(key:string,fn:()=>Promise<unknown>,success:string){setBusy(key);setError('');try{await fn();notify.success(success);await load()}catch(e){const message=getApiError(e,'Action failed. Please retry.');setError(message);notify.error(message)}finally{setBusy('')}}
  async function submitCancel(){const reason=cancelReason.trim();if(!reason){setCancelReasonError('Cancellation reason is required.');return}if(reason.length>500){setCancelReasonError('Cancellation reason must be 500 characters or fewer.');return}setCancelReasonError('');setBusy('cancel');setError('');try{await purchasesAPI.cancelOrder(id,reason);setCancelDialog(false);setCancelReason('');notify.success('Purchase order cancelled.');await load()}catch(e){const message=getApiError(e,'Could not cancel this purchase order.');setError(message);notify.error(message)}finally{setBusy('')}}
  async function createReceipt(){if(!po)return;const items=receipt.filter(x=>Number(x.receivedQuantity)>0).map(x=>({purchaseOrderItemId:x.purchaseOrderItemId,receivedQuantity:Number(x.receivedQuantity),acceptedQuantity:Number(x.acceptedQuantity),rejectedQuantity:Number(x.rejectedQuantity),damageQuantity:Number(x.damageQuantity),batchNumber:x.batchNumber||undefined,expiryDate:x.expiryDate||undefined}));if(!items.length){setError('Enter a received quantity for at least one item.');return}if(items.some(x=>x.receivedQuantity!==x.acceptedQuantity+x.rejectedQuantity+x.damageQuantity)){setError('For every line, received quantity must equal accepted + rejected + damaged.');return}if(items.some(x=>po.items.find(i=>i.id===x.purchaseOrderItemId)?.requiresExpiry&&x.acceptedQuantity>0&&(!x.batchNumber||!x.expiryDate))){setError('Batch number and expiry date are required for accepted items with expiry tracking.');return}await act('grn',()=>purchasesAPI.createGrn({purchaseOrderId:id,items}), 'Goods received note recorded. It is pending acceptance.');}
  async function beginGrnEdit(grnId:string){setBusy(`load-grn-${grnId}`);setError('');try{const note=await purchasesAPI.grn(grnId);setGrnEditLines(note.items.map(item=>({purchaseOrderItemId:item.purchaseOrderItemId,receivedQuantity:String(item.receivedQuantity),acceptedQuantity:String(item.acceptedQuantity),rejectedQuantity:String(item.rejectedQuantity),damageQuantity:String(item.damageQuantity)})));setEditingGrn(grnId)}catch(e){const message=getApiError(e,'Could not load this receipt for editing.');setError(message);notify.error(message)}finally{setBusy('')}}
  async function saveGrnEdit(grnId:string){const items=grnEditLines.map(line=>({purchaseOrderItemId:line.purchaseOrderItemId,receivedQuantity:Number(line.receivedQuantity),acceptedQuantity:Number(line.acceptedQuantity),rejectedQuantity:Number(line.rejectedQuantity),damageQuantity:Number(line.damageQuantity)}));if(items.some(item=>Object.values(item).some(value=>typeof value==='number'&&(!Number.isFinite(value)||value<0)))){setError('Receipt quantities must be valid non-negative numbers.');return}if(items.some(item=>item.receivedQuantity!==item.acceptedQuantity+item.rejectedQuantity+item.damageQuantity)){setError('For every line, received quantity must equal accepted + rejected + damaged.');return}setBusy(`save-grn-${grnId}`);setError('');try{await purchasesAPI.updateGrn(grnId,{items});setEditingGrn('');notify.success('Goods received note updated.');await load()}catch(e){const message=getApiError(e,'Could not update this receipt.');setError(message);notify.error(message)}finally{setBusy('')}}
  if(loading)return <div className="flex items-center justify-center gap-2 rounded-2xl border bg-white p-12 text-sm text-[#73766f]"><Loader2 className="animate-spin" size={18}/>Loading purchase order…</div>;
  if(!permissions.includes('purchases.view'))return <Gate text="Your account does not have the purchases.view permission."/>;
  if(!po)return <Gate text={error||'Purchase order not found.'}/>;
  const canReceive=['ORDERED','PARTIALLY_RECEIVED'].includes(po.status);
  return <div className="mx-auto w-full max-w-6xl min-w-0 space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard/purchases" className="inline-flex items-center gap-2 text-sm font-medium text-[#63685f] hover:text-[#20211f]"><ArrowLeft size={16}/>Back to purchases</Link>{po.status==='DRAFT'&&permissions.includes('purchases.edit')&&<Link href={`/dashboard/purchases/orders/${id}/edit`} className="inline-flex min-h-10 items-center rounded-xl border border-[#dfe2da] bg-white px-4 text-sm font-semibold text-[#32352e] transition hover:border-[#829600] hover:text-[#647500]">Edit draft</Link>}</div>
    {error&&<div role="alert" className="flex items-start gap-2 rounded-xl border border-[#efd4cf] bg-[#fff7f5] p-4 text-sm text-[#9b3730]"><AlertCircle size={18} className="shrink-0"/>{error}<button onClick={()=>void load()} className="ml-auto underline">Reload</button></div>}
    <header className="flex flex-col gap-4 rounded-2xl border border-[#e6e8e1] bg-white p-5 shadow-sm sm:flex-row sm:items-start sm:justify-between sm:p-7"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#738900]">Purchase order</p><h1 className="mt-2 break-all text-2xl font-semibold sm:text-3xl">{po.poNumber}</h1><p className="mt-2 text-sm text-[#73766f]">{po.supplierName} · {po.locationName} · Ordered {new Date(po.orderDate).toLocaleDateString()}</p>{po.expectedDeliveryDate&&<p className="mt-1 text-sm text-[#73766f]">Expected delivery · {new Date(po.expectedDeliveryDate).toLocaleDateString()}</p>}{po.referenceNumber&&<p className="mt-1 break-words text-sm text-[#73766f]">Reference · {po.referenceNumber}</p>}<p className="mt-3"><span className="rounded-full bg-[#eef2e2] px-3 py-1.5 text-xs font-bold text-[#53620e]">{po.status.replace(/_/g,' ')}</span></p></div><div className="grid grid-cols-2 gap-3 text-right"><Summary label="Total" value={purchaseMoney(po.totalAmount)}/><Summary label="Balance due" value={purchaseMoney(po.balanceDue)}/></div></header>
    <section className="overflow-hidden rounded-2xl border border-[#e6e8e1] bg-white shadow-sm"><div className="border-b border-[#eceee8] px-5 py-4"><h2 className="font-semibold">Items</h2></div><div className="divide-y divide-[#eceee8]">{po.items.map(item=><div key={item.id} className="grid gap-2 p-4 sm:grid-cols-[minmax(0,1fr)_repeat(4,auto)] sm:items-center sm:px-5"><div className="min-w-0"><p className="truncate font-semibold">{item.productName}</p><p className="text-xs text-[#73766f]">{item.productSku} · {item.quantity} ordered</p></div><p className="text-sm">{purchaseMoney(item.unitPrice)} / unit</p><p className="text-sm">Line {purchaseMoney(item.lineTotal)}</p><p className="text-sm text-[#73766f]">Accepted {item.grnReceivedQty}</p><p className="text-sm font-medium">{item.outstandingQty} outstanding</p></div>)}</div><div className="mx-3 my-3 grid gap-2 rounded-2xl border border-[#e7e1c9] bg-[#f4f1e7] p-4 text-sm shadow-sm sm:ml-auto sm:mr-4 sm:w-80"><MoneyLine label="Subtotal" value={po.subtotal}/><MoneyLine label="Shipping" value={po.shippingCost}/><MoneyLine label="Tax" value={po.taxAmount}/><MoneyLine label="Paid" value={po.totalPaid}/><MoneyLine label="Balance" value={po.balanceDue} bold/></div>{po.notes&&<p className="border-t p-4 text-sm text-[#73766f]">{po.notes}</p>}</section>
    <div className="grid gap-5 lg:grid-cols-2">
      <section className="space-y-4 rounded-2xl border border-[#e6e8e1] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><PackageCheck className="text-[#738900]" size={19}/><h2 className="text-lg font-semibold">Receiving</h2></div>{permissions.includes('purchases.approve')&&grns.some(g=>g.status==='RECEIVED')&&<div className="space-y-2 rounded-xl bg-[#f5f6f2] p-3"><p className="text-sm font-semibold">Pending quality acceptance</p>{grns.filter(g=>g.status==='RECEIVED').map(g=><div className="flex flex-wrap items-center justify-between gap-2" key={g.id}><span className="text-sm">{g.grnNumber} · {g.totalAcceptedQty} accepted</span><div className="flex gap-2"><button disabled={!!busy} onClick={()=>void act(`accept-${g.id}`,()=>purchasesAPI.acceptGrn(g.id),'Receipt accepted; stock has been updated.')} className="rounded-lg bg-[#e7f4ed] px-3 py-2 text-xs font-bold text-[#16734a] disabled:opacity-50">Accept</button><button disabled={!!busy} onClick={()=>{const reason=window.prompt('Reason for rejecting this receipt?');if(reason!==null)void act(`reject-${g.id}`,()=>purchasesAPI.rejectGrn(g.id,reason),'Receipt rejected.')}} className="rounded-lg bg-[#fff0ed] px-3 py-2 text-xs font-bold text-[#a63832] disabled:opacity-50">Reject</button></div></div>)}</div>}
        {canReceive&&permissions.includes('purchases.create')&&<><p className="text-sm text-[#73766f]">Record quantities delivered; only accepted quantities enter stock after approval.</p>{receipt.map((line,index)=>{const item=po.items.find(i=>i.id===line.purchaseOrderItemId)!;return <div key={line.purchaseOrderItemId} className="space-y-2 rounded-xl border border-[#eceee8] p-3"><div className="flex justify-between gap-2 text-sm"><span className="font-semibold">{item.productName}{item.requiresExpiry&&<span className="ml-2 text-xs font-medium text-[#93600c]">Batch and expiry required</span>}</span><span className="text-[#73766f]">Open {item.outstandingQty}</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{(['receivedQuantity','acceptedQuantity','rejectedQuantity','damageQuantity'] as const).map((field,i)=><label key={field} className="text-[11px] text-[#73766f]">{['Received','Accepted','Rejected','Damaged'][i]}<input type="number" min="0" step="0.01" value={line[field]} onChange={e=>setReceipt(rows=>rows.map((r,j)=>j===index?{...r,[field]:e.target.value}:r))} className={`${input} mt-1 px-2`}/></label>)}</div>{item.requiresExpiry&&<div className="grid grid-cols-2 gap-2"><label className="text-[11px] text-[#73766f]">Batch number<input value={line.batchNumber} onChange={e=>setReceipt(rows=>rows.map((r,j)=>j===index?{...r,batchNumber:e.target.value}:r))} className={`${input} mt-1`}/></label><label className="text-[11px] text-[#73766f]">Expiry date<input type="date" value={line.expiryDate} onChange={e=>setReceipt(rows=>rows.map((r,j)=>j===index?{...r,expiryDate:e.target.value}:r))} className={`${input} mt-1`}/></label></div>}</div>})}<button disabled={!!busy||!receipt.length} onClick={()=>void createReceipt()} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-transparent bg-[#20211f] px-4 text-sm font-semibold text-white shadow-sm transition hover:bg-[#343632] hover:shadow-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#738900] disabled:opacity-50 dark:border-[#596347] dark:bg-[#050605] dark:text-[#e7e9e3] dark:hover:border-[#829600] dark:hover:bg-[#111510] dark:hover:shadow-[0_0_18px_rgba(216,240,75,0.12)] dark:focus-visible:outline-[#d8f04b]">{busy==='grn'?<Loader2 className="animate-spin" size={16}/>:<PackageCheck size={16}/>}Record goods received</button></>}
        {!canReceive&&<p className="text-sm text-[#73766f]">This order is not open for more goods receipts.</p>}
        <div className="border-t border-[#eceee8] pt-3"><p className="mb-2 text-sm font-semibold">Recorded receipts</p>{grns.map(g=><div key={g.id} className="space-y-2 border-b border-[#eceee8] py-3 last:border-0"><div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>{g.grnNumber} · {g.totalAcceptedQty}/{g.totalReceivedQty} accepted/received</span><span className="text-[#73766f]">{g.status}</span></div>{editingGrn===g.id?<><div className="space-y-2">{grnEditLines.map((line,index)=><div key={line.purchaseOrderItemId} className="grid grid-cols-2 gap-2 sm:grid-cols-4">{(['receivedQuantity','acceptedQuantity','rejectedQuantity','damageQuantity'] as const).map((field,i)=><label key={field} className="text-[11px] text-[#73766f]">{['Received','Accepted','Rejected','Damaged'][i]}<input aria-label={`${g.grnNumber} ${['received','accepted','rejected','damaged'][i]} quantity`} type="number" min="0" step="0.01" value={line[field]} onChange={event=>setGrnEditLines(rows=>rows.map((row,rowIndex)=>rowIndex===index?{...row,[field]:event.target.value}:row))} className={`${input} mt-1 px-2`}/></label>)}</div>)}</div><div className="flex gap-2"><button disabled={!!busy} onClick={()=>void saveGrnEdit(g.id)} className="min-h-9 rounded-lg bg-[#20211f] px-3 text-xs font-bold text-white disabled:opacity-50">{busy===`save-grn-${g.id}`?'Saving…':'Save changes'}</button><button disabled={!!busy} onClick={()=>setEditingGrn('')} className="min-h-9 rounded-lg border px-3 text-xs font-semibold">Cancel</button></div></>:g.status==='RECEIVED'&&permissions.includes('purchases.edit')?<button disabled={!!busy} onClick={()=>void beginGrnEdit(g.id)} className="min-h-9 rounded-lg border border-[#dfe2da] px-3 text-xs font-semibold disabled:opacity-50">{busy===`load-grn-${g.id}`?'Loading…':'Edit receipt'}</button>:null}</div>)}{!grns.length&&<p className="text-sm text-[#73766f]">No receipts yet.</p>}</div>
      </section>
      <div className="space-y-5"><section className="space-y-3 rounded-2xl border border-[#e6e8e1] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><Wallet className="text-[#738900]" size={19}/><h2 className="text-lg font-semibold">Supplier payment</h2></div>{permissions.includes('payments.create')&&po.balanceDue>0?<><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Amount<input type="number" min="0.01" max={po.balanceDue} step="0.01" value={payAmount} onChange={e=>setPayAmount(e.target.value)} className={`${input} mt-1`}/></label><label className="text-xs font-semibold">Payment method<select value={methodId} onChange={e=>setMethodId(e.target.value)} className={`${input} mt-1`}><option value="">Select method</option>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><button disabled={!!busy||!methodId||Number(payAmount)<=0||Number(payAmount)>po.balanceDue} onClick={()=>void act('payment',()=>purchasesAPI.payment(id,{amount:Number(payAmount),paymentMethodId:methodId}),'Payment recorded.') } className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#20211f] px-4 text-sm font-semibold text-white disabled:opacity-50">{busy==='payment'&&<Loader2 className="animate-spin" size={15}/>}Record payment</button>{!methods.length&&<p className="text-xs text-[#93600c]">No active payment methods found or settings.view access is missing.</p>}</>:<p className="text-sm text-[#73766f]">{po.balanceDue<=0?'This order is fully paid.': 'Your account cannot record supplier payments.'}</p>}</section>
      <section className="space-y-3 rounded-2xl border border-[#e6e8e1] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><RotateCcw className="text-[#738900]" size={19}/><h2 className="text-lg font-semibold">Supplier returns</h2></div>{permissions.includes('purchases.create')&&po.items.some(i=>i.grnAcceptedQty>i.returnedQty)?<><label className="text-xs font-semibold">Received item<select value={returnItem} onChange={e=>setReturnItem(e.target.value)} className={`${input} mt-1`}><option value="">Select item</option>{po.items.filter(i=>i.grnAcceptedQty>i.returnedQty).map(i=><option key={i.id} value={i.id}>{i.productName} · max {Math.max(0,i.grnAcceptedQty-i.returnedQty)}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Quantity<input type="number" min="0.01" step="0.01" max={Math.max(0,...po.items.filter(i=>i.id===returnItem).map(i=>i.grnAcceptedQty-i.returnedQty))} value={returnQty} onChange={e=>setReturnQty(e.target.value)} className={`${input} mt-1`}/></label><label className="text-xs font-semibold">Reason<select value={returnReason} onChange={e=>setReturnReason(e.target.value as typeof returnReason)} className={`${input} mt-1`}>{returnReasons.map(r=><option key={r}>{r}</option>)}</select></label></div><button disabled={!!busy||!returnItem||Number(returnQty)<=0||Number(returnQty)>Math.max(0,...po.items.filter(i=>i.id===returnItem).map(i=>i.grnAcceptedQty-i.returnedQty))} onClick={()=>void act('return',()=>purchasesAPI.createReturn({purchaseOrderId:id,items:[{purchaseOrderItemId:returnItem,quantity:Number(returnQty),reason:returnReason}]}),'Return request created as draft.') } className="min-h-10 rounded-xl bg-[#20211f] px-4 text-sm font-semibold text-white disabled:opacity-50">Create return request</button></>:<p className="text-sm text-[#73766f]">{permissions.includes('purchases.create')?'No accepted quantity is available to return.':'Your account cannot create supplier returns.'}</p>}
        {returns.map(ret=><div key={ret.id} className="flex flex-wrap items-center justify-between gap-2 border-t border-[#eceee8] pt-3 text-sm"><span>{ret.returnNumber} · {ret.status} · {purchaseMoney(ret.totalReturnAmount)}</span>{ret.status==='DRAFT'&&permissions.includes('purchases.approve')&&<div className="flex gap-2"><button disabled={!!busy} onClick={()=>void act(`ret-approve-${ret.id}`,()=>purchasesAPI.approveReturn(ret.id),'Supplier return approved and stock reduced.')} className="rounded-lg bg-[#e7f4ed] px-3 py-2 text-xs font-bold text-[#16734a]">Approve</button><button disabled={!!busy} onClick={()=>{const reason=window.prompt('Reason for rejecting this return?');if(reason!==null)void act(`ret-reject-${ret.id}`,()=>purchasesAPI.rejectReturn(ret.id,reason),'Supplier return rejected.')}} className="rounded-lg bg-[#fff0ed] px-3 py-2 text-xs font-bold text-[#a63832]">Reject</button></div>}</div>)}{!returns.length&&<p className="text-sm text-[#73766f]">No returns recorded.</p>}</section>
      </div>
    </div>
    <section className="flex flex-wrap gap-2 rounded-2xl border border-[#e6e8e1] bg-white p-4 shadow-sm">{po.status==='DRAFT'&&permissions.includes('purchases.approve')&&<button disabled={!!busy} onClick={()=>void act('approve',()=>purchasesAPI.approveOrder(id),'Purchase order approved and sent to the supplier.')} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#e7f4ed] px-4 text-sm font-semibold text-[#16734a] transition hover:bg-[#dcefe4] hover:underline disabled:opacity-50"><Check size={16}/>Approve order</button>}{!['CANCELLED','FULLY_RECEIVED','CLOSED'].includes(po.status)&&permissions.includes('purchases.cancel')&&<button disabled={!!busy} onClick={()=>{setCancelReason('');setCancelReasonError('');setCancelDialog(true)}} className="min-h-10 rounded-xl border border-[#efd4cf] px-4 text-sm font-semibold text-[#a63832] transition hover:bg-[#fff7f5] hover:underline disabled:opacity-50">Cancel order</button>}<button onClick={()=>void load()} className="ml-auto min-h-10 rounded-xl border border-[#dfe2da] px-4 text-sm font-semibold transition hover:bg-[#f5f6f2] hover:underline">Refresh</button></section>
    {cancelDialog&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#11140f]/35 p-4 backdrop-blur-[2px]" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)setCancelDialog(false)}}><section role="dialog" aria-modal="true" aria-labelledby="cancel-order-title" className="w-full max-w-lg rounded-2xl border border-[#e6e8e1] bg-white p-5 shadow-2xl dark:border-[#343a33] dark:bg-[#191d19] sm:p-6"><h2 id="cancel-order-title" className="text-lg font-semibold text-[#20211f] dark:text-[#e7e9e3]">Cancel purchase order</h2><p className="mt-2 text-sm text-[#73766f] dark:text-[#aeb5aa]">Enter a reason for cancelling {po.poNumber}. This will be recorded with the order.</p><label htmlFor="cancel-order-reason" className="mt-4 block text-sm font-medium text-[#32352e] dark:text-[#dce1d7]">Cancellation reason</label><textarea id="cancel-order-reason" autoFocus maxLength={500} rows={4} value={cancelReason} onChange={event=>{setCancelReason(event.target.value);if(cancelReasonError)setCancelReasonError('')}} className="mt-1 w-full resize-y rounded-xl border border-[#dfe2da] bg-white px-3 py-2 text-sm text-[#20211f] outline-none focus:border-[#829600] focus:ring-2 focus:ring-[#d8f04b]/40 dark:border-[#3b423a] dark:bg-[#111510] dark:text-[#e7e9e3]" placeholder="Why is this order being cancelled?" aria-describedby={cancelReasonError?'cancel-order-reason-error':'cancel-order-reason-count'}/>{cancelReasonError?<p id="cancel-order-reason-error" role="alert" className="mt-1 text-sm text-[#a63832]">{cancelReasonError}</p>:<p id="cancel-order-reason-count" className="mt-1 text-right text-xs text-[#73766f] dark:text-[#aeb5aa]">{cancelReason.length}/500</p>}<div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" disabled={!!busy} onClick={()=>setCancelDialog(false)} className="min-h-10 rounded-xl border border-[#dfe2da] px-4 text-sm font-semibold text-[#32352e] transition hover:bg-[#f5f6f2] disabled:opacity-50 dark:border-[#3b423a] dark:text-[#dce1d7] dark:hover:bg-[#252a24]">Keep order</button><button type="button" disabled={!!busy} onClick={()=>void submitCancel()} className="min-h-10 rounded-xl bg-[#a63832] px-4 text-sm font-semibold text-white transition hover:bg-[#8f302b] disabled:opacity-50">{busy==='cancel'?'Cancelling…':'Confirm cancellation'}</button></div></section></div>}
  </div>;
}
function Summary({label,value}:{label:string;value:string}){return <div><p className="text-xs text-[#73766f]">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
function MoneyLine({label,value,bold}:{label:string;value:number;bold?:boolean}){return <div className={`flex justify-between ${bold?'font-bold':''}`}><span>{label}</span><span>{purchaseMoney(value)}</span></div>}
function Gate({text}:{text:string}){return <section className="mx-auto max-w-2xl rounded-2xl border border-[#efd4cf] bg-white p-7 text-center"><AlertCircle className="mx-auto text-[#a63832]"/><h1 className="mt-3 text-xl font-semibold">Purchase order unavailable</h1><p className="mt-2 text-sm text-[#73766f]">{text}</p><Link href="/dashboard/purchases" className="mt-5 inline-flex min-h-10 items-center rounded-xl bg-[#20211f] px-4 text-sm font-semibold text-white">Back to purchases</Link></section>}
